'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {AlignLeft,ArrowUpRight,Upload,ShieldCheck,Clock3,MessagesSquare,CalendarDays,Heart,RotateCcw,BarChart3} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Switch} from '@/components/ui/switch';

import {analyse,demoChat,duration,parseChat,type Message} from '@/lib/chat';
import {ReplyExpress} from '@/components/reply-express';
import {AiInsights} from '@/components/ai-insights';
const periods=['All Time','Last 3 Days','Last 7 Days','This Month','Previous Calendar Month','Last 30 Days','Custom Range'];
function Pick({label,value,options,onChange}:{label:string,value:string,options:string[],onChange:(v:string)=>void}){return <label className="field">{label}<Select value={value} onValueChange={onChange}><SelectTrigger className="select" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o} value={o}>{o}</SelectItem>)}</SelectContent></Select></label>}
function track(event:string){void fetch('/api/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event}),keepalive:true}).catch(()=>{});}
export default function Home(){
 const [chat,setChat]=useState<Message[]>([]),[demo,setDemo]=useState(false),[kind,setKind]=useState('Friend'),[period,setPeriod]=useState('All Time'),[order,setOrder]=useState('Auto-detect'),[gap,setGap]=useState('6 hours'),[night,setNight]=useState(true),[excludeStart,setExcludeStart]=useState('23:00'),[excludeEnd,setExcludeEnd]=useState('07:00'),[customStart,setCustomStart]=useState(''),[customEnd,setCustomEnd]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[raw,setRaw]=useState(''),[filename,setFilename]=useState('');
 // Distinct default avatars keep the two participants visible in the token chart.
 // Visitors can change either avatar; participant names never determine gender.
 const [avatars,setAvatars]=useState(['👦🏻','🙎🏻‍♀️']),[selectedDay,setSelectedDay]=useState<string|null>(null);
 const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{track('page_view');},[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'set_conversation_period',description:'Set the visible date filter for the conversation dashboard.',inputSchema:{type:'object',properties:{period:{type:'string',enum:periods.filter(p=>p!=='Custom Range')}},required:['period'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(v:any)=>{if(!periods.includes(v.period)||v.period==='Custom Range')throw Error('Unsupported period');setPeriod(v.period);track('filter_used');return {period:v.period};}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort();},[]);
 const bounds=useMemo(()=>{const now=new Date(),end=+now;let start=0,finish=end;if(period==='All Time')finish=Infinity;else if(period==='This Month')start=+new Date(now.getFullYear(),now.getMonth(),1);else if(period==='Previous Calendar Month'){start=+new Date(now.getFullYear(),now.getMonth()-1,1);finish=+new Date(now.getFullYear(),now.getMonth(),1)-1;}else if(period==='Custom Range'){start=customStart?+new Date(customStart+'T00:00:00'):0;finish=customEnd?+new Date(customEnd+'T23:59:59.999'):end;}else start=end-(period==='Last 3 Days'?3:period==='Last 7 Days'?7:30)*86400000;return {start,end:finish};},[period,customStart,customEnd]);
 const timeMinutes=(value:string)=>{const [hours,minutes]=value.split(':').map(Number);return hours*60+minutes;};
 const result=useMemo(()=>analyse(chat,bounds.start,bounds.end,gap==='All gaps'?Infinity:gap==='24 hours'?1440:gap==='6 hours'?360:120,night,timeMinutes(excludeStart),timeMinutes(excludeEnd)),[chat,bounds,gap,night,excludeStart,excludeEnd]);
 // Compute the busiest day once so large exports stay responsive.
 const busiestDay=result.days.reduce((peak,day)=>Math.max(peak,day.A+day.B),1);
 const [a,b]=result.stats;const total=result.filtered.length;const ratio=(n:number,d:number)=>d?`${Math.round(n/d*100)}%`:'—';const rate=(n:number,d:number)=>d?(n/d*100).toFixed(1):'—';
 async function upload(file:File|undefined){if(!file)return;setError('');if(!file.name.toLowerCase().endsWith('.txt')){setError('Choose the .txt file inside your WhatsApp export. Unzip the export first if needed.');track('import_failed');return;}if(file.size>15*1024*1024){setError('Please choose an export smaller than 15 MB.');return;}setBusy(true);track('import_started');try{const text=await file.text();setRaw(text);setChat([]);setDemo(false);setFilename(file.name);const messages=parseChat(text,order==='Auto-detect'?'AUTO':order.startsWith('Day')?'DMY':'MDY');setChat(messages);setFilename(file.name);setDemo(false);setPeriod('All Time');track('import_completed');}catch(e){setError((e as Error).message);track('import_failed');}finally{setBusy(false);if(input.current)input.current.value='';}}
 function sample(){setChat(demoChat());setDemo(true);setRaw('');setFilename('Illustrative conversation');setError('');setPeriod('All Time');track('demo_opened');}
 function changeOrder(v:string){setOrder(v);if(raw)try{setChat(parseChat(raw,v==='Auto-detect'?'AUTO':v.startsWith('Day')?'DMY':'MDY'));setDemo(false);setPeriod('All Time');setError('');track('import_completed');}catch(e){setError((e as Error).message);}}
 function clear(){setChat([]);setRaw('');setFilename('');setDemo(false);setError('');track('chat_cleared');}
 const pair=(label:string,x:any,y:any)=> <div className="row" key={label}><span>{label}</span><span><strong>{x}</strong></span><span>{y}</span></div>;
 return <><header><a href="/" className="brand"><span className="mark"><AlignLeft size={23}/></span>between lines<span style={{color:'#a56f83'}}>.</span></a><nav className="nav"><a className="active" href="#insights">Your insights</a><a className="hide" href="#method">How it works</a><a href="/analytics" aria-label="Owner analytics"><BarChart3 size={19}/></a></nav></header>
 <main className={kind==='Partner'?'romantic':''}><div className="intro"><div><div className="eyebrow">A little perspective on your conversations</div><h1>A little sunshine for your conversations{kind==='Partner'?' ♡':'.'}</h1><p>Two people. Little hellos. A story only you can tell.</p></div><span className="pill"><ShieldCheck size={16}/>Local analysis · AI sharing is optional</span></div>
 <section className="card upload"><div><h2>{chat.length?'A fresh look at your connection.':'Start with a conversation.'}</h2><p>Import a WhatsApp personal chat to compare the timing, effort and warmth on both sides. No relationship score. Just a clearer picture.</p><div className="inline"><button className="secondary" onClick={sample}>Explore a sample <ArrowUpRight size={15}/></button>{chat.length>0&&<button className="secondary" onClick={clear}><RotateCcw size={14}/>Clear chat</button>}</div><p><a href="#method">How to export your WhatsApp chat →</a></p></div><div className="drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void upload(e.dataTransfer.files[0]);}}><Upload size={25} color="#8a3d59"/><strong>{busy?'Reading your conversation…':'Drop your WhatsApp .txt here'}</strong><small>Personal DMs only · Up to 15 MB · Without media</small><input ref={input} type="file" accept=".txt,text/plain" hidden onChange={e=>void upload(e.target.files?.[0])}/><p style={{fontSize:12,lineHeight:1.5,margin:0}}>By uploading a chat, you agree that you’re a participant and have obtained the necessary permission to analyse it. Only personal DMs are allowed; detected group chats will be rejected.</p><button disabled={busy} className="primary" onClick={()=>input.current?.click()}>Choose a chat file</button></div></section>
 {error&&<div role="alert" className="error">{error}</div>}
 <div id="insights" className="controls"><div className="choices"><Pick label="Relationship" value={kind} options={['Partner','Friend','Family','Colleague','Other']} onChange={v=>{setKind(v);track('relationship_changed');}}/><Pick label="Time period" value={period} options={periods} onChange={v=>{setPeriod(v);track('filter_used');}}/><Pick label="Export date format" value={order} options={['Auto-detect','Day / Month / Year','Month / Day / Year']} onChange={changeOrder}/></div>{chat.length>0&&<div className="field">{demo?<span className="pill">Sample data · not a real relationship</span>:<span className="pill">Chat imported · analysed locally</span>}<small>{new Date(chat[0].at).toLocaleDateString()} – {new Date(chat.at(-1)!.at).toLocaleDateString()}</small></div>}</div>
 {period==='Custom Range'&&<div className="inline" style={{marginBottom:20}}><label className="field">From<input className="input" type="date" value={customStart} onChange={e=>setCustomStart(e.target.value)}/></label><label className="field">Through<input className="input" type="date" value={customEnd} onChange={e=>setCustomEnd(e.target.value)}/></label></div>}
 <div className="filters"><label><Switch checked={night} onCheckedChange={v=>{setNight(v);track('filter_used');}} aria-label="Exclude response gaps during a custom period"/>Exclude response gaps during this period</label><label className="field">Exclude from<input className="input" type="time" value={excludeStart} disabled={!night} onChange={e=>{if(e.target.value){setExcludeStart(e.target.value);track('filter_used');}}}/></label><label className="field">Exclude until<input className="input" type="time" value={excludeEnd} disabled={!night} onChange={e=>{if(e.target.value){setExcludeEnd(e.target.value);track('filter_used');}}}/></label>{night&&excludeStart===excludeEnd&&<small>Matching start and end times exclude no period.</small>}<Pick label="Response gaps to include" value={gap} options={['2 hours','6 hours','24 hours','All gaps']} onChange={v=>{setGap(v);track('filter_used');}}/><small>Dates use your browser’s local time. Recent periods end today.</small></div>
 {!chat.length?<div className="card empty"><MessagesSquare size={34} style={{margin:'auto',color:'#a0667b'}}/><h2 style={{marginTop:18}}>👦🏻 💬 🙎🏻‍♀️ Two perspectives. One conversation.</h2><p className="muted">Import a chat or explore the sample to see your communication profile.</p><div className="inline" style={{justifyContent:'center',marginTop:24}}>{['Responsiveness','Initiative','Effort','Warmth','Consistency'].map(t=><span className="pill" key={t}>{t}</span>)}</div></div>:!total?<div className="card empty"><h2>No messages in this period</h2><p className="muted">Try All Time or choose dates within your exported conversation.</p></div>:<>
 <section className="connection-cast" aria-label="Personalise your conversation"><div className="cast-heading"><span aria-hidden="true">✨</span><h2>The cast of your chats 🤝🏻</h2><small>Choose an avatar for each person. Just for this visit.</small></div><div className="cast-pair">{[a,b].map((person,i)=><div className={'person person-'+i} key={person.who}><span className="avatar" aria-hidden="true">{avatars[i]}</span><div><h3>{person.who}</h3><div className="avatar-choices" role="group" aria-label={`Avatar for ${person.who}`}>{['👦🏻','🙎🏻‍♀️','🧑🏻','🌻','🐻','🐱'].map(emoji=><button key={emoji} aria-label={`Choose ${emoji} for ${person.who}`} aria-pressed={avatars[i]===emoji} onClick={()=>setAvatars(current=>current.map((v,j)=>j===i?emoji:v))}>{emoji}</button>)}</div></div></div>)}</div></section><div className="summary"><div className="card"><div className="stat-label">Messages exchanged<MessagesSquare size={17}/></div><div className="stat">{total.toLocaleString()}</div><small>{a.messages.toLocaleString()} / {b.messages.toLocaleString()} by participant</small></div><div className="card"><div className="stat-label">Typical reply time<Clock3 size={17}/></div><div className="stat">{duration(a.median)} <span style={{fontSize:17,color:'#bba0ab'}}>/</span> {duration(b.median)}</div><small>Median · {a.replies.length} / {b.replies.length} eligible replies</small></div><div className="card"><div className="stat-label">Conversation starters<ArrowUpRight size={17}/></div><div className="stat">{a.starts} <span style={{fontSize:17,color:'#bba0ab'}}>/</span> {b.starts}</div><small>After a pause of at least 6 hours</small></div><div className="card"><div className="stat-label">Days you connected<CalendarDays size={17}/></div><div className="stat">{result.days.length}</div><small>{result.days.filter(d=>d.A&&d.B).length} days with messages from both</small></div></div>
 <div className="grid"><section className="card"><div className="section-title"><div><h2>The rhythm of your conversation</h2><small>A garden of the days you showed up</small></div><span className="pill">Activity</span></div><div className="garden-key"><span>🌱 A quieter day</span><span>🌼 A little back-and-forth</span><span>🌻 A busy conversation</span></div>{/* Every flower represents one active day; thresholds are relative to this period. */}<div className="conversation-garden" aria-label="Active days in your conversation">{result.days.map(day=>{const share=(day.A+day.B)/busiestDay;return <button className={selectedDay===day.day?'flower selected':'flower'} key={day.day} aria-label={`${day.day}: ${a.who} ${day.A} messages, ${b.who} ${day.B} messages`} aria-pressed={selectedDay===day.day} onClick={()=>setSelectedDay(day.day)}><span aria-hidden="true">{share>.66?'🌻':share>.33?'🌼':'🌱'}</span><small>{day.day.slice(5)}</small></button>;})}</div><div className="garden-detail" aria-live="polite">{(()=>{const day=result.days.find(d=>d.day===selectedDay);return day?<><strong>{day.day}</strong><span>{avatars[0]} {a.who}: {day.A} messages</span><span>{avatars[1]} {b.who}: {day.B} messages</span></>:<span>👆 Pick a flower to revisit that day’s rhythm.</span>;})()}</div><small>One flower per active day. Flower types reflect message counts relative to the busiest day in this period. Silent days are omitted.</small></section>
 <ReplyExpress people={result.stats} avatars={avatars}/>
 <section className="card"><h2>A shared conversation</h2><small>Balance shows participation, not who cares more.</small><div style={{marginTop:20}}><div className="inline" style={{justifyContent:'space-between'}}><span>{a.who} · {ratio(a.messages,total)}</span><span>{b.who} · {ratio(b.messages,total)}</span></div>{/* Twenty tokens approximate the split; the percentages above remain exact rounded values. */}<div className="message-circle" aria-label="Message participation in twenty tokens">{Array.from({length:20},(_,i)=><span className={i<Math.round(a.messages/total*20)?'token token-a':'token token-b'} aria-hidden="true" key={i}>{i<Math.round(a.messages/total*20)?avatars[0]:avatars[1]}</span>)}</div><small>Each character represents about 5% of messages.</small></div>{pair('Conversations initiated',a.starts,b.starts)}{pair('Days active',a.days,b.days)}{pair('Words sent',a.words.toLocaleString(),b.words.toLocaleString())}<div className="note">{a.starts===b.starts?'Both participants start the same number of conversations in this period.':`${a.starts>b.starts?a.who:b.who} starts more conversations in this period.`} Different roles, schedules and messaging styles can explain an uneven split.</div></section>
 <section className="card"><h2>Effort in the details</h2><small>Observable text patterns, without a “quality” verdict</small>{pair('Words per text',a.texts?(a.words/a.texts).toFixed(1):'—',b.texts?(b.words/b.texts).toFixed(1):'—')}{pair('Words per turn',a.turnWords.toFixed(1),b.turnWords.toFixed(1))}{pair('Detailed texts (20+ words)',a.detail,b.detail)}{pair('Detailed texts / 100 texts',rate(a.detail,a.texts),rate(b.detail,b.texts))}{pair('Texts with a question / 100',rate(a.questions,a.texts),rate(b.questions,b.texts))}<small>A question mark is a proxy for questions, not proof of a follow-up.</small></section>
 <section className="card full"><div className="section-title"><div><h2>Your usual first words 💬</h2><small>The top three messages when each person starts a new conversation</small></div><span className="pill">Your way of saying hello</span></div><div className="grid" style={{marginTop:24}}>{[a,b].map((person,i)=><div key={person.who}><h3>{avatars[i]} {person.who}</h3>{person.openers.length?person.openers.map(([word,n],rank)=><div className={"phrase-bubble bubble-"+i} key={word} style={{marginBottom:14}}><div className="inline" style={{justifyContent:'space-between'}}><span><small>{rank+1}.</small> <strong>“{person.openerExamples[word]}”</strong></span><small>{n} {n===1?'time':'times'} · {ratio(n,person.openerCount)}</small></div></div>):<p className="muted">No text openers in this period.</p>}<small>{person.openerCount} text conversation starts analysed</small></div>)}</div><div className="note">A new conversation begins after at least 6 hours of silence, or at the start of the export. Case and punctuation are ignored; “hello” and “hellooo” stay separate. Emoji-only and media-only starts have no word and are excluded. Percentages use all eligible text starts, not just the top five.</div></section>
 <section className="card full"><div className="section-title"><div><h2>Your usual last words 👋🏻</h2><small>The top three messages before a conversation goes quiet</small></div><span className="pill">How you sign off</span></div><div className="grid" style={{marginTop:24}}>{[a,b].map((person,i)=><div key={person.who}><h3>{avatars[i]} {person.who}</h3>{person.closers.length?person.closers.map(([word,n],rank)=><div className={"phrase-bubble bubble-"+i} key={word} style={{marginBottom:14}}><div className="inline" style={{justifyContent:'space-between'}}><span><small>{rank+1}.</small> <strong>“{person.closerExamples[word]}”</strong></span><small>{n} {n===1?'time':'times'} · {ratio(n,person.closerCount)}</small></div></div>):<p className="muted">No eligible closings in this period.</p>}<small>{person.closerCount} text conversation endings analysed</small></div>)}</div><div className="note">A closing is the last word before a pause of at least 6 hours, regardless of who starts next. The final message in the export is excluded because we cannot observe the next gap. This shows last words, not necessarily deliberate goodbyes. Case and punctuation are ignored; media-only and emoji-only endings are excluded.</div></section>
<AiInsights chat={chat}/><section className="card full"><div className="section-title"><div><h2>Small ways to connect better</h2><small>Personalised from this period’s patterns · locally generated guidance</small></div><span className="pill">Try, don’t assume</span></div><div className="grid" style={{marginTop:24}}><div><h3>Share the first hello</h3><p className="muted" style={{lineHeight:1.7}}>{a.starts+b.starts<4?'There are too few conversation starts to infer a reliable pattern. Start with what feels comfortable to both of you.':Math.max(a.starts,b.starts)/(a.starts+b.starts)>.65?`${a.starts>b.starts?a.who:b.who} initiates most conversations here. If it feels one-sided to either of you, the other person could initiate the next check-in with a specific question.`:'Both of you contribute to starting conversations. Keep creating openings that invite a response, rather than aiming for an exact 50/50 split.'}</p><div className="note">{kind==='Colleague'?'“How did the presentation go? Is there anything I can help with?”':'“You mentioned a busy week—how did that thing you were working on go?”'}</div></div><div><h3>Make response expectations explicit</h3><p className="muted" style={{lineHeight:1.7}}>{a.replies.length<5||b.replies.length<5?'Reply samples are small. Discuss availability rather than drawing conclusions from the current times.':`Your typical reply gaps are ${duration(a.median)} and ${duration(b.median)}. If the difference causes friction, discuss busy hours and what counts as urgent; matching speeds is not a goal.`}</p><div className="note">“I may be slow to reply during the day. If something is time-sensitive, what’s the best way for us to flag it?”</div></div><div><h3>Respond to the substance</h3><p className="muted" style={{lineHeight:1.7}}>Text length reflects style, not caring. When someone shares something important, acknowledge one specific detail and ask an open question. A thoughtful sentence can do more than a paragraph.</p><div className="note">“That sounds like it took a lot of effort. What part mattered most to you?”</div></div><div><h3>Close the loop warmly</h3><p className="muted" style={{lineHeight:1.7}}>Your closing-word patterns show how exchanges pause, not whether someone meant to end them. If pauses feel abrupt, try a brief sign-off and an honest expectation about reconnecting.</p><div className="note">{kind==='Partner'?'“I loved catching up. I’m heading off now—shall we talk tomorrow?”':'“Good catching up. I need to head off now—let’s pick this up when we’re both free.”'}</div></div></div><div className="note"><strong>Locally generated suggestions.</strong> These suggestions use transparent rules and your local metrics, not an AI model. They are conversation prompts, not a diagnosis or a judgement of either person.</div></section>
 <section className="card full"><div className="section-title"><div><h2>{kind==='Partner'?'Affection & appreciation':'Warmth & support'}</h2><small>Recognised phrases in English and a small set of Romanised Hindi expressions</small></div>{kind==='Partner'&&<Heart size={22} color="#a64a6b"/>}</div>{pair('Appreciation & support · matching texts',a.warm,b.warm)}{pair('Appreciation & support / 100 texts',rate(a.warm,a.texts),rate(b.warm,b.texts))}{kind==='Partner'&&<>{pair('Affection · matching texts',a.affection,b.affection)}{pair('Affection / 100 texts',rate(a.affection,a.texts),rate(b.affection,b.texts))}</>}<div className="note">Phrase matches are signals, not a reading of intent. Nicknames, sarcasm, negation and other languages can be missed or misread. Longer texts and faster replies do not necessarily mean a stronger relationship.</div></section></div></>}
 <details id="method" className="card details"><summary>How to export your chat & understand the numbers</summary><p><strong>Export:</strong> In WhatsApp, open the personal conversation and find Export Chat in the chat’s settings or More menu. Choose Without Media, save the export, and select its .txt file here. If you receive a .zip, extract it first. Menu locations vary by device.</p><p><strong>Response time:</strong> Consecutive messages by the same person form a turn until a 6-hour gap. A response is measured from the previous person’s last message to the next person’s first. Both must lie in the selected period. There is no read-receipt information in an export, so this measures the gap between sent messages—not time after reading. Unanswered final messages do not count as replies.</p><p><strong>Filters:</strong> The excluded-period filter removes response intervals overlapping your chosen daily times (default 11 pm–7 am). It supports periods crossing midnight; matching times exclude nothing. Long-gap filters remove intervals over the selected threshold. All Time covers the full export; recent ranges end now. Previous Calendar Month and Last 30 Days are different ranges. Timestamps follow the export’s local clock, interpreted in this browser’s time zone.</p><p><strong>Text metrics:</strong> Media and deleted-message placeholders are excluded from text-length and phrase metrics but included in message activity. Detailed texts contain at least 20 whitespace-separated words. Fully contained turns are used for words-per-turn. Warmth and affection use a limited phrase dictionary, not an AI psychological assessment. Export omissions and low sample sizes can skew results.</p><p><strong>Privacy:</strong> Local analysis keeps your chat on this device. Optional AI analysis sends messages and timestamps from the last three calendar months to Cloudflare only after separate consent. Speaker headers become A/B; identifying details inside message text may remain. Our AI backend does not save chats or results. For local analysis, chat contents, filenames, participant names and relationship type are not sent to our server. They stay in this tab’s memory until you clear the chat or close/reload the page. Anonymous event counters record page loads, import success/failure, demo use and filter use. They contain no chat information, IP address, persistent visitor ID or message statistics. Hosting infrastructure may separately keep operational request logs.</p></details><footer className="footer"><span>between lines. · Understand the conversation, not judge the connection.</span><a href="/analytics">Owner analytics ↗</a></footer></main></>;
}
