import {useMemo,useState} from 'react';
import {analyse,duration,type Message} from '../lib/chat';
import {giftPatterns,replyBuckets} from '../lib/gift-patterns';
const hourLabel=(hour:number)=>`${hour%12||12}${hour<12?'am':'pm'}–${(hour+1)%12||12}${(hour+1)%24<12?'am':'pm'}`;
export function GiftInsights({chat}:{chat:Message[]}){
 const [night,setNight]=useState(true);
 // Memoisation keeps the one-second unlock countdown from recalculating chat analysis.
 const result=useMemo(()=>analyse(chat,0,Infinity,360,night),[chat,night]);const patterns=useMemo(()=>giftPatterns(chat),[chat]);
 const avatar=(who:string,index:number)=>(who.toLowerCase().includes('muskan')?'👧':'👦')+'🏻';
 return <><section className="connection-cast"><h2>The cast of our chats 🤝</h2><div className="cast-pair">{result.stats.map((person,index)=><div className={'person person-'+index} key={person.who}><span className="avatar">{avatar(person.who,index)}</span><div><h3>{person.who}</h3></div></div>)}</div></section>
 <section className="card"><div className="section-title"><div><h2>The reply express 🚀</h2><small>From the last message in one person’s turn to the other person’s reply · gaps up to 6 hours</small></div></div><label className="reply-filter"><input type="checkbox" checked={night} onChange={e=>setNight(e.target.checked)}/>Skip reply gaps overlapping 11pm–7am</label><div className="reply-people">{result.stats.map((person,index)=><div className={'reply-person reply-person-'+index} key={person.who}><div className="reply-person-heading"><span>{avatar(person.who,index)}</span><div><h3>{person.who}</h3><small>{person.replies.length} replies measured</small></div></div><div className="reply-ticket"><small>Typical reply · median</small><strong>{duration(person.median)}</strong></div><div className="reply-stops">{replyBuckets(person.replies).map(stop=><div className="reply-stop" key={stop.label}><span className="stop-icon">{stop.icon}</span><span>{stop.label}</span><div><strong>{person.replies.length?Math.round(stop.count/person.replies.length*100)+'%':'—'}</strong><small>{stop.count} {stop.count===1?'reply':'replies'}</small></div></div>)}</div></div>)}</div></section>
 <section className="card"><h2>Who starts, who signs off? 👋</h2><small>New exchanges and last messages before a pause of at least 6 hours</small><div className="pause-pair">{patterns.people.map((person,index)=><div className={'pause-person bubble-'+index} key={person.who}><h3>{avatar(person.who,index)} {person.who}</h3><div className="pause-number"><span>First hello</span><strong>{person.starts}</strong></div><div className="pause-number"><span>Last message before a pause</span><strong>{person.endings}</strong></div><span className="pill">{patterns.completed?Math.round(person.endings/patterns.completed*100)+'% of observed sign-offs':'No completed pauses yet'}</span></div>)}</div></section>
 {(['openers','closers'] as const).map(type=><section className="card" key={type}><h2>{type==='openers'?'Our usual first words 💬':'Our usual last words 👋'}</h2><div className="phrase-pair">{patterns.people.map((person,index)=><div key={person.who}><h3>{avatar(person.who,index)} {person.who}</h3>{person[type].length?person[type].map(phrase=><div className={'phrase-bubble bubble-'+index} key={phrase.word}><div className="phrase-word">“{phrase.word}” <small>{phrase.count} {phrase.count===1?'time':'times'}</small></div><small>🕰️ Most often around {hourLabel(phrase.hour)}</small></div>):<small>No {type==='openers'?'first':'last'} words yet.</small>}</div>)}</div><small>Times follow the chat export’s clock. The final message isn’t counted as a sign-off.</small></section>)}</>;
}
